name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees:
  - riverma
body:
  - type: markdown
    attributes:
      value: |
        > _Thank you for filing a bug ticket. We very much appreciate your time._
  - type: checkboxes
    id: checked
    attributes:
      label: Checked for duplicates
      description: By submitting this issue, you confirm you've already scanned the list of existing issues in this repository and not found duplicates
      options:
        - label: I've checked existing issues 
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Screenshots welcome.
      placeholder: Tell us what you saw
      value: "When I did XYZ action, I noticed XYZ..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect?
      description: A clear and concise description of what you expect to happen
      placeholder: Tell us what you want
      value: "When I do XYZ action, I expect XYZ..."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Which environment did you experience this bug in?"
      value: |
        - Version of this software [e.g. vX.Y.Z]
        - Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
        ...
      render: bash
