name: New Feature
description: Submit a new feature request
title: "[New Feature]: "
labels: ["enhancement", "needs triage"]
assignees:
  - riverma
body:
  - type: markdown
    attributes:
      value: |
        > _Thank you for filing a new feature request. We very much appreciate your time._
  - type: dropdown
    id: checked-duplicates
    attributes:
      label: Checked for duplicates
      description: Have you already scanned the [list of existing issues](https://github.com/riverma/github_test_area/issues?q=is%3Aissue) for duplicates?
      multiple: false
      options:
        - 'yes'
        - 'no'
    validations:
      required: yes
  - type: checkboxes
    id: checked-alternatives
    attributes:
      label: Alternatives considered
      description: By submitting this issue, you confirm you've already considered alternative solutions to your need
      options:
        - label: I confirm I've considered alternatives and determined they do not suffice
          required: true
  - type: textarea
    id: feature-problem
    attributes:
      label: Related problem
      description: Is your feature request related to a problem? Please help us understand if so.
      placeholder: Tell us the problem
      value: "Ex. I'm frustrated when [...] happens"
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature request
      description: A clear and concise description of your request. 
      placeholder: Tell us what you want
      value: "Ex. I need or want [...]"
    validations:
      required: true
