name: Other Issue
description: Submit a general/other issue request
labels: ["needs triage"]
assignees:
  - riverma
body:
  - type: checkboxes
    id: checked-duplicates
    attributes:
      label: Checked for duplicates
      description: By submitting this issue, you confirm you've already scanned the [list of existing issues](https://github.com/riverma/github_test_area/issues?q=is%3Aissue) and not found duplicates
      options:
        - label: I confirm this issue is new
          required: true
  - type: checkboxes
    id: checked-not-bug-feature
    attributes:
      label: Not a bug or feature request
      description: By submitting this issue, you confirm this ticket is not a bug or feature request but another type of issue or support issue for a bug or feature request
      options:
        - label: I confirm this is not a bug or feature request
          required: true
  - type: input
    id: support
    attributes:
      label: Support
      description: "Is this issue related to another ticket? If so which?"
      placeholder: "e.g. [#2]"
    validations:
      required: false
  - type: textarea
    id: task-description
    attributes:
      label: Describe the task request
      description: A clear and concise description of your request. 
      placeholder: Tell us what you want
      value: "I need [...] to support [...]"
    validations:
      required: true
